name: EasyNames
main: com.shadow.eznames.EasyNames
version: 1.0
description: Handles names
author: ShadowHunter1123
commands:
    ez:
       description: Commands
permissions:   
    ez.*:
        default: op
        children:
            ez.nick: true
            ez.colorname: true
            ez.nameitem: true
            ez.colornameitem: true
            ez.colorname: true
            ez.tag: true
            ez.help: true
            ez.colors: true
            ez.tagtypes: true

    ez.nick: 
        default: op
    ez.colorname:
        default: op
    ez.nameitem:
        default: op       
    ez.coloritemname:
        default: op
    ez.tag:
        default: op
    ez.help:
        default: op
    ez.colors:
        default: op
    ez.tagtypes:
        default: op
    ez.reset:
        default: op
      
                        